### ISSUE TITLE
6-Add a feature for users to customize the Joke Parameters

### ISSUE THREAD

**Issue by ionescu77** [LuisJoseSanchez/encode-club-ai-and-gpt-bootcamp-q3-homework-week2#3]
Add a feature for users to customize the Joke Parameters
## Part 1
- [x] Choose which parameters you'd like to offer your users
- [x] For example, allow users to select:
    - A genre from a list of options (fantasy, mistery, romance, SF, etc.)
    - A tone for the joke (witty, sarcastic, silly, dark, goofy, etc.)
- [x] Consider how you'll construct the prompt for the AI model to adhere to these parameters

## Part 2
    - The type of joke (pun, knock-knock, story, etc.)
    - The "temperature" (how much randomness/creativity to add to the joke)

I think previous code from Example 5 needs to be modified
